config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'gossips#index'
  resources :users
  resources :gossips
  resources :static_pages
  resources :user_profile
  resources :cities, only: [:index, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments
  resources :gossips do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :gossip
    belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_many :gossip_tags
    has_many :tags, through: :gossip_tags
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
    belongs_to :tag
    belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossip_tags
    has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    belongs_to :city
    has_many :gossips
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
    @users = @city.users
    @gossips = Gossip.where(user: @users)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:index, :show]
  def create
    comment = Comment.create(post_params)
    redirect_to comment_path(comment.id)
  end

  def destroy
    @comment = Gossip.find(params[:id])
    @comment.destroy
    redirect_to gossips_path
  end

  def new
    @comment = Comment.new
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(post_params)
      redirect_to comments_path
    else
      render :edit
    end
  end

  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  private

  def post_params
    params.require(:gossip).permit(:title, :content, :user_id)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :show]
  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    gossip = Gossip.create(post_params)
    redirect_to gossip_path(gossip.id)
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(post_params)
      redirect_to gossips_path
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
  
  def post_params
    params.require(:gossip).permit(:title, :content, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id#.to_s
      flash[:success] = "Connexion réussie !"
      redirect_to user_profile_path

    else
      flash[:failure] = 'Combinaison mail/mot de passe incorrect'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: "Déconnecté!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def team
    end
  
    def contact
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:create]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @city = City.find(@user.city_id)
    @gossips = User.find(@user.id).gossips
  end

  def new
    @user = User.new
    @cities = City.all
  end

  def create
    @user = User.new(params.permit(:first_name, :last_name, :email, :age, :description, :password,))
    @user.city_id = 1
    if @user.save
      flash[:success] = "Compte bien créé !"
      redirect_to root_path
    else
      flash[:failure] = "Erreur lors de la création du compte !"
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
      end
    
       def log_in(user)
        session[:user_id] = user.id
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cities</title>
  </head>
  <body>
    <div class="d-flex justify-content-center">
      <div class="col">
        <% @cities.each do |city| %>
          <div class="list-group">
            <a href="<%= city_path(city.id) %>" class="list-group-item list-group-item-action">
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1"><%= city.name%></h5>
              </div>
            </a>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/cities/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @city.name%></title>
  </head>
  <body>
    <div class="container mt-3">
      <div class="row">
        <div class="col-sm-3 well">
          <div class="card">
            <h5 class="card-header">Les informations sur <%= @city.name%></h5>
            <p class="m-2">
              - <%= @city.name%><br>
              - <%= @city.zip_code%>
            </p>
            <h5 class="card-header">Ses gosseurs</h5>
            <div class="m-2" >
              <% @users.each do |user| %>
              <div class="list-group-item list-group-item-action">
                <%= link_to user.first_name + " " + user.last_name, user_path(user.id), class: "btn" %>
              </div>
              <% end %>
            </div>
          </div>
        </div>    
        <div class="col-sm-4">
          <div class="list-group">
            <% @gossips.each do |gossip| %>
              <a href="<%= gossip_path(gossip.id) %>" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1"><%= gossip.title %></h5>
                  <small><%= gossip.created_at %></small>
                </div>
                <p class="mb-1">
                  <%= gossip.content %> 
                </p>
              </a>
            <% end %>
          </div>
        </div>
      </div>               
    </div>
  </body>
</html>

app/views/comments/edit.html.erb
<h1>Editer le commentaire</h1>
<%= form_for @gossip do |f| %>
 <div class="form-group">
  <label>Contenu du commentaire</label>
  <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <button type="submit">Modifier le commentaire</button>
  </div>
<% end %>

app/views/comments/index.html.erb
<% @comments.each do |comment| %>
    <div>
      <div>
        <%= comment.content %>
        <small><%= comment.update_at</small>
      </div>
      <div class="row justify-content-center">
        <%= link_to "V", edit_comment_path, class: "btn btn-primary" %><%= link_to "X", comment_path(comment.id), :class => "btn btn-danger", :method => :delete, :confirm => "Are you sure?" %>
      </div>
    
    </div>
    <% end %>

app/views/comments/new.html.erb
<h1>Créer le commentaire</h1>
<%= form_for @comment do |f| %>
 <div class="form-group">
  <label>Commentaire</label>
  <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <button type="submit">Créer le commentaire</button>
  </div>
<% end %>

app/views/comments/show.html.erb
<%= link_to "V", edit_comment_path, class: "btn btn-primary" %><%= link_to "O", edit_comment_path, class: "btn btn-success" %><%= link_to "Delete", gossip_path(@gossip.id), :class => "btn btn-danger", :method => :delete, :confirm => "Are you sure?" %>
<%= button_to "+", new_comment_path, :method => "get", class:'btn btn-success' %>

app/views/gossips/create.html.erb
<h1>Gossips#create</h1>
<p>Find me in app/views/gossips/create.html.erb</p>

app/views/gossips/edit.html.erb
<h1>Editer le gossip</h1>
<%= form_for @gossip do |f| %>
 <div class="form-group">
   <label>Titre du gossip</label>
   <%= f.text_field :title, class: 'form-control' %>
 </div>
 <div class="form-group">
  <label>Contenu du gossip</label>
  <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <button type="submit">Modifier le gossip</button>
  </div>
<% end %>

app/views/gossips/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gossips</title>
  </head>
  <body>
    <h1 class="display-4">Welcome to my Gossip Project</h1>
    <p class="lead">La communauté, le partage, les potins : les copains quoi !</p>

    <!-- Listes des gossips -->
    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col" style="width:100%;">
            <% @gossips.each do |gossip| %>
              <div class="card shadow-sm">
                <div class="card-body">
                  <a href"<%= gossip_path(gossip.id) %>" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                      <h5 class="mb-1"><%= gossip.title %></h5>
                      <small><%= gossip.created_at %></small>
                    </div>
                    <p class="mb-1">
                      <%= gossip.content %> 
                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </a>
                </div>
              </div>
            </div>      
          <% end %>
        </div>
      </div>
    </div>
 </body>
</html>

app/views/gossips/new.html.erb
<h1>Créer le gossip</h1>
<%= form_for @gossip do |f| %>
 <div class="form-group">
   <label>Titre du gossip</label>
   <%= f.text_field :title, class: 'form-control' %>
 </div>
 <div class="form-group">
  <label>Contenu du gossip</label>
  <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <button type="submit">Créer le gossip</button>
  </div>
<% end %>

app/views/gossips/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @gossip.title%></title>
  </head>
  <body>
    <div class="d-flex justify-content-center">
      <div class="card col-sm-4 m-4">
        <%= @gossip.title%><br>
        <%= @gossip.content%><br>
        <small>
          <%= @gossip.created_at%> by <%= link_to "voir le créateur", user_path(@gossip.user_id)%>
        </small>
        <div class="row justify-content-center">
          <%= link_to "Modifier un gossip", edit_gossip_path, class: "btn btn-primary" %><%= link_to "Delete", gossip_path(@gossip.id), :class => "btn btn-danger", :method => :delete, :confirm => "Are you sure?" %>
        </div>
        <% @gossip.comments.each do |comment| %>
        <div class="well">
          <p><%= comment.content %></p>
        </div>
        <% end %>
        <div class="well">
          <%= button_to "+", new_gossip_comment_path(@gossip.id), :method => "get", class:'btn btn-success' %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Users</title>
  </head>
  <body>
    <div class="card-columns w-100 p-3">
      <% @users.each do |user| %>
        <div class="card">
          <div class="card-header">
            <%= user.first_name%> <%= user.last_name%>
          </div>
          <div class="card-body">
            <blockquote class="blockquote mb-0">
              <p><%= user.description%></p>
              <footer class="blockquote-footer bg-transparent"><%= user.created_at%> <%= link_to "see more about", user_path(user.id)%></footer>
            </blockquote>
          </div>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Remplit le questionnaire pour t'inscrire</h1>
<%= form_tag url_for(action: 'create'), method: "post" do %>

<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <%= label_tag 'Prénom :' %>
      <%= text_field_tag 'first_name' %>
      <br /> <br />

      <%= label_tag 'Nom :' %>
      <%= text_field_tag 'last_name'%>
      <br /> <br />

      <%= label_tag 'Mail :' %>
      <%= text_field_tag 'email'%>
      <br /> <br />

      <%= label_tag 'Âge :' %>
      <%= number_field_tag 'age'%>
      <br /> <br />

      <%= label_tag 'Bio :' %>
      <%= text_area_tag 'description'%>
      <br /> <br />

      <%= label_tag 'Mot de passe : ' %><br />
      <%= password_field_tag 'password'%>
      <br /> <br />

      <%= submit_tag "Créer mon compte" %>

    <% end %>

<% if @user.errors.any? %>
  <p>Nous n'avons pas réussi à créer un utilisateur pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @user.first_name%> <%= @user.last_name%></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
      html, body {
        height: 100%;
        margin: 0; padding: 0;
      }
      body {
        display : table;
        width: 100%;
      }
      footer {
        display : table-row;
        height: 50px; /* à titre d'exemple */
        background-color: #555;
        color: white;
        padding: 10px;
      }
    </style>
  </head>
  <body>
    <div class="container text-center">    
      <div class="row">
        <div class="col-sm-3 well">
          <div class="well">
            <table class="table">
              <thead>
                <td><%= @user.first_name%> <%= @user.last_name%></td>
              </thead>
              <tbody>
                <tr>
                  <td><%= @user.age%> ans</td>
                </tr>
                <tr>
                  <td><%= link_to @user.city.name, city_path(@user.city.id), class: "btn" %></td>
                </tr>
                <tr>
                  <td><%= @user.description %></td>
                </tr>
                
              </tbody>
            </table>
          </div>
          <div class="well">
            <p>Mes Tags</p>
            <p>
              <span class="label label-default">News</span>
              <span class="label label-primary">W3Schools</span>
              <span class="label label-success">Labels</span>
              <span class="label label-info">Football</span>
              <span class="label label-warning">Gaming</span>
              <span class="label label-danger">Friends</span>
            </p>
          </div>
          <!-- <div class="alert alert-success fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
            <p><strong>Ey!</strong></p>
            People are looking at your profile. Find out who.
          </div> -->
        </div>

        


        <div class="col-sm-7">
          <div class="col-sm-12">
            <div class="row">
              <div class="col-sm-12">
                <div class="well">
                  <%= button_to "Creer un gossip", new_gossip_path, :method => "get", class:'btn btn-success' %>
                </div>
              </div>
            </div>
          </div>
          <% @gossips.each do |gossip| %>
            <div class="row">
              <div class="col-sm-3">
                <div class="well">
                  <p>
                    <%= gossip.title %><br>
                    <small><%= gossip.created_at %></small>
                  </p>
                </div>
              </div>
              <div class="col-sm-9">
                <div class="well">
                  <p><%= gossip.content %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>







        <div class="col-sm-2 well">
          <div class="thumbnail">
            <p>Upcoming Events:</p>
            <img src="paris.jpg" alt="Paris" width="400" height="300">
            <p><strong>Paris</strong></p>
            <p>Fri. 27 November 2015</p>
            <button class="btn btn-primary">Info</button>
          </div>      
          <div class="well">
            <p>ADS</p>
          </div>
          <div class="well">
            <p>ADS</p>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>