config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'gossips#index'
  resources :users
  resources :gossips
  resources :static_pages
  resources :user_profile
  resources :cities, only: [:index, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments
  resources :gossips do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :gossip
    belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_many :gossip_tags
    has_many :tags, through: :gossip_tags
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
    belongs_to :tag
    belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossip_tags
    has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    belongs_to :city
    has_many :gossips
    has_many :comments
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
    @users = @city.users
    @gossips = Gossip.where(user: @users)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:index, :show]
  def create
    comment = Comment.create(post_params)
    redirect_to comment_path(comment.id)
  end

  def destroy
    @comment = Gossip.find(params[:id])
    @comment.destroy
    redirect_to gossips_path
  end

  def new
    @comment = Comment.new
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(post_params)
      redirect_to comments_path
    else
      render :edit
    end
  end

  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  private

  def post_params
    params.require(:gossip).permit(:title, :content, :user_id)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :show]
  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    gossip = Gossip.create(post_params)
    redirect_to gossip_path(gossip.id)
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(post_params)
      redirect_to gossips_path
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
  
  def post_params
    params.require(:gossip).permit(:title, :content, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id#.to_s
      flash[:success] = "Connexion réussie !"
      redirect_to user_profile_path

    else
      flash[:failure] = 'Combinaison mail/mot de passe incorrect'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: "Déconnecté!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:create]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @city = City.find(@user.city_id)
    @gossips = User.find(@user.id).gossips
  end

  def new
    @user = User.new
    @cities = City.all
  end

  def create
    @user = User.new(params.permit(:first_name, :last_name, :email, :age, :description, :password,))
    @user.city_id = 1
    if @user.save
      flash[:success] = "Compte bien créé !"
      redirect_to root_path
    else
      flash[:failure] = "Erreur lors de la création du compte !"
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
      end
    
       def log_in(user)
        session[:user_id] = user.id
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rorformat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Gossip</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
          </button>
  
          <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
               <a class="nav-link active" aria-current="page" href="<%= gossips_path %>">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= static_pages_path %>" >Team</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= static_pages_path%>">Contact</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false">S inscrire / Se connecter</a>
                  <ul class="dropdown-menu" aria-labelledby="dropdown01">
                    <li><a class="dropdown-item" href="<%= new_session_path %>">Se connecter</a></li>
                    <li><a class="dropdown-item" href="<%= new_user_path %>" >S'inscrire</a></li>
                  </ul>
              </li>
            </ul
          </div>
        </div>
      </nav>
    </header>

    <main>
      <section class="py-5 text-center container">
        <div class="row py-lg-5">
          <div class="col-lg-6 col-md-8 mx-auto">
          </div>
        </div>
        <%= yield %>
        </br>
      </section>
    </main>

    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Gossip project™  by,  CharlesCmt©   ®2021</p>
      </div>
    </footer>
  </body>
</html>

app/views/user_profile/user_profile.html.erb
<h2>Bienvenue  current_user !</h2>
<h3>Profil de <%= @user.full_name%></h3>
<div class="ml-2">
  <p><span class="attribute">Prénom: </span>
    <%= @user.first_name %></p>
  <p><span class="attribute">Nom: </span>
    <%= @user.last_name %></p>
  <p><span class="attribute">Email: </span>
    <%= @user.email %></p>
  <p><span class="attribute">Ville de résidence: </span>
    <%= @user.city.name %></p>
  <p><span class="attribute">Description: </span>
    <%= @user.description %></p>
</div>

app/views/welcome/user.html.erb
<h2>Bienvenue <%= User.find_by(id: session[:user_id]).first_name %> !</h2>
<p>Ici c'est notre super site de potins, il est chouette, non ?</p>